sudo: false
language: ruby
rvm:
- 2.4.2
before_install: gem install bundler -v 1.16.1
script:
- bundle exec rake build
deploy:
  provider: rubygems
  api_key:
    secure: Tx5oMTJEvhYh2iZM4q3Z2yRxE2oTSQVU8ZcAgrYkhDpv0cw8+qdO5B3lIxTRsRAsQUJvWqtWf+0Tc45zxf4N7h1YegRYm7ECYLnupK1Ij+A2yXH6RlZmzUc47EScxYgQXEd7oufumjPgCCC1Qbr5+F7ypj/u08hdneEuaWF5dZKcigiJmr6xTwFsbwZvrS8fDVQgurvtrmyn2Y2MbQZ53TlVy+jF5erqD76j6gbyuQwmWR0zgI0tuglgK8RvTXYrUzMKm3UI708Q+7oz/VR0xXaRsSoTZE4nLEFvGAjiov9/SAsPb6f8QDWos2Mj/BsGSDVBPAvR/MPvNgDyFM2YQYMQG3X9zUo0MeuYEHPKX34KvPXi3cOANu9j4Xz7MRJPOvnSekE06kFICqZpZXtUoDXdfVR5fiXD+8Dc8kWEYR9/7P7cN9ZrPwVY083jocvrwo4zgzdJAR4ITIpUx+QUCltHu17RYUT4AEfz41vzG3KhozLVyZvbbxJNeZkBqnGWulmFQP7dUVxN/XDghWeuki9s46KbXMbJn4mqcWzEML9FA7tDTqI7c5QvK0nBLc1so2laoXitsBLqnCENsTB7iGUB//91TGi+v9RbVaV0CKyqAQK88+ypeW9+4SEdWQSyHTXHA3n3HNU5UJjGZSRJvW6ZNYBi/ssz86TR+DHWZDU=
  on:
    master: true
  gem: vagrant-json-plugin
